Repository afes-website/cappuccino-app, pull requests merged in 2021-11, with the labels that each got.

#201 #200 docs のバージョンを v3.3.3 に
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
  yarn.lock
Labels: enhancement, dependencies

#209 #207 CheckIn のロジックを src/hooks に切り出した
  src/components/AccountDrawer.tsx
  src/components/AccountIcon.tsx
  src/components/ActivityLogTimeline.tsx
  src/components/AuthContext.tsx
  src/components/BottomNav.tsx
  src/components/ExhInfoCard.tsx
  src/components/GuestScan.tsx
  src/components/PermissionList.tsx
  src/components/SideNav.tsx
  src/components/StayStatus.tsx
  src/components/StayStatusCard.tsx
  src/components/TopBar.tsx
  src/hooks/auth/@types.ts
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useRequirePermission.ts
  src/hooks/useCheckRsv.ts
  src/hooks/useErrorHandler.ts
  src/hooks/useExhibitionImageUrl.tsx
  src/hooks/useHandleRsvScan.ts
  src/hooks/useReset.ts
  src/hooks/useWristBandColor.ts
  src/layouts/Main.tsx
  src/libs/themeMode.ts
  src/pages/Account.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/LoginWithQR.tsx
  src/pages/executive/AllExhStatus.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/CheckOutScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/executive/RegisterSpare.tsx
  src/pages/exhibition/EnterScan.tsx
  src/pages/exhibition/ExitScan.tsx
  src/pages/exhibition/ScanHistory.tsx
Labels: refactor

#206 #205 予約IDを直接入力できるようにした
  src/hooks/useHandleRsvInput.ts
  src/pages/executive/CheckInScan.tsx
Labels: bug

#204 #172 ヒートマップ複数教室対応
  src/components/CongestionHeatMap.tsx
Labels: enhancement

#216 #202 GuestInfo の予約確認機能拡充
  src/pages/Home.tsx
  src/pages/executive/GuestInfo.tsx
Labels: enhancement

#217 #214 入場スキャン保護者対応
  src/pages/executive/CheckInScan.tsx
Labels: enhancement

#219 #213 予備リストバンド登録を新形式の予約QRに対応
  src/pages/executive/RegisterSpare.tsx
Labels: enhancement

#220 #157 入退室画面で展示滞在状況を表示する
  src/components/ExhInfoCard.tsx
  src/components/GuestScan.tsx
  src/components/StayStatusCard.tsx
  src/pages/Home.tsx
Labels: enhancement

#221 Release v3.3.1 to dev
  package.json
Labels: release

#228 #224 長過ぎる Guest ID はスキャンを受け付けないように
  src/hooks/useErrorHandler.ts
  src/pages/executive/CheckInScan.tsx
Labels: enhancement

#232 #215 scrollTop が壊れていたのを修正
  src/components/LayoutWrapper.tsx
Labels: bug

#231 #121 CLS 修正
  src/components/ReloadButton.tsx
  src/components/StayStatusCard.tsx
Labels: bug

#230 #226 直接入力ボタンの位置を修正
  src/layouts/Tablet.tsx
Labels: bug

#227 #218 check-in の UI 改善
  src/assets/child.svg
  src/assets/logo.svg
  src/assets/person.svg
  src/components/StayStatus.tsx
  src/components/TicketHeader.tsx
  src/hooks/useWristBandColor.ts
  src/libs/stringDateJp.ts
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/executive/RegisterSpare.tsx
  src/types/global.d.ts
Labels: enhancement, design

#235 Release v3.3.2 to dev
  README.md
  package.json
  yarn.lock
Labels: release

#234 Release v3.3.2
  README.md
  package.json
  src/assets/child.svg
  src/assets/logo.svg
  src/assets/person.svg
  src/components/LayoutWrapper.tsx
  src/components/ReloadButton.tsx
  src/components/StayStatus.tsx
  src/components/StayStatusCard.tsx
  src/components/TicketHeader.tsx
  src/hooks/useErrorHandler.ts
  src/hooks/useWristBandColor.ts
  src/layouts/Tablet.tsx
  src/libs/stringDateJp.ts
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/executive/RegisterSpare.tsx
  src/types/global.d.ts
  yarn.lock
Labels: release

#229 #223 展示内満員時の表示
  src/components/GuestScan.tsx
  src/components/QRScanner.tsx
  src/components/ResultPopup.tsx
  src/components/StayStatusCard.tsx
  src/hooks/useDots.ts
  src/pages/exhibition/EnterScan.tsx
  src/types/statusColor.ts
Labels: enhancement

#237 #178 react-qr-reader による out of memory の暫定的な解決
  src/components/QRScanner.tsx
Labels: bug

#239 Release v3.3.3
  package.json
  src/components/GuestScan.tsx
  src/components/QRScanner.tsx
  src/components/ResultPopup.tsx
  src/components/StayStatusCard.tsx
  src/hooks/useDots.ts
  src/pages/exhibition/EnterScan.tsx
  src/types/statusColor.ts
Labels: release

#240 Release v3.3.3 to dev
  package.json
Labels: release
