Repository afes-website/cappuccino-app, pull requests merged in 2021-09, with the labels that each got.

#130 #129 /auth/me に変更・/reservations/_id/check の認証外し
  package.json
  src/components/AuthContext.tsx
  src/pages/executive/CheckInScan.tsx
  yarn.lock
Labels: enhancement

#132 #128 401 エラー対応
  src/App.tsx
  src/components/ActivityLogTimeline.tsx
  src/components/AuthContext.tsx
  src/components/ExhInfoCard.tsx
  src/components/StayStatusCard.tsx
  src/libs/auth/useAuth.ts
  src/libs/useExhibitionImageUrl.tsx
  src/pages/Login.tsx
  src/pages/executive/AllExhStatus.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/CheckOutScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/exhibition/EnterScan.tsx
  src/pages/exhibition/ExitScan.tsx
  src/pages/exhibition/ScanHistory.tsx
Labels: enhancement

#134 #133 allUsers を使用順にソート
  src/components/AuthContext.tsx
Labels: enhancement

#124 #123 スキャン時に効果音を鳴らす
  src/assets/sounds/error.mp3
  src/assets/sounds/success.mp3
  src/components/ResultChip.tsx
  src/libs/audio.ts
  src/pages/executive/GuestInfo.tsx
  src/types/global.d.ts
Labels: enhancement

#135 #120 混雑状況ヒートマップ
  src/components/CongestionHeatMap.tsx
  src/components/SideNav.tsx
  src/components/TopBar.tsx
  src/layouts/Tablet.tsx
  src/libs/congestionColor.ts
  src/libs/paletteColor.ts
  src/libs/routes.ts
  src/libs/wristBandColor.ts
  src/pages/executive/HeatMap.tsx
Labels: enhancement

#143 #140 PermissionList の切り出し
  src/components/AccountDrawer.tsx
  src/components/PermissionList.tsx
  src/components/SideNav.tsx
  src/pages/Account.tsx
Labels: refactor

#139 #138 スキャンを高速化
  src/components/QRScanner.tsx
Labels: enhancement

#137 #127 QRコードログイン
  src/components/AccountIcon.tsx
  src/components/GuestScan.tsx
  src/components/QRScanner.tsx
  src/components/TopBar.tsx
  src/libs/routes.ts
  src/pages/Login.tsx
  src/pages/LoginWithQR.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
Labels: enhancement

#145 #136 エラー時のダイアログを廃止しアラートに統一
  src/components/ErrorAlert.tsx
  src/components/GuestScan.tsx
  src/libs/errorHandler.ts
  src/libs/useErrorHandler.ts
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
Labels: bug, refactor

#144 #141 アカウント系デザインをいい感じに
  src/components/AccountDrawer.tsx
  src/components/AccountIcon.tsx
  src/components/SideNav.tsx
  src/pages/Account.tsx
Labels: enhancement, design

#151 #150 依存関係更新祭り
  .husky/pre-commit
  .prettierrc.js
  package.json
  src/App.tsx
  src/libs/auth/useAuth.ts
  src/libs/themeMode.ts
  src/libs/useErrorHandler.ts
  src/setupTests.ts
  yarn.lock
Labels: dependencies
