Repository afes-website/cappuccino-app, pull requests merged in 2021-07, with the labels that each got.

#91 #83 複数人予約に対応
  src/components/GuestScan.tsx
  src/components/ResultPopup.tsx
  src/libs/errorHandler.ts
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
  yarn.lock
Labels: enhancement

#93 #78 でざいんりにゅーある
  package.json
  public/index.html
  src/assets/scss/main.scss
  src/assets/styles/theme.ts
  src/components/BottomNav.tsx
  src/components/ExhInfoCard.tsx
  src/components/GuestScan.tsx
  src/components/StayStatus.tsx
  src/components/TopBar.tsx
  src/layouts/Main.tsx
  src/libs/themeMode.ts
  src/pages/Home.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/exhibition/ScanHistory.tsx
  yarn.lock
Labels: design, enhancement, iOS

#95 #94 useAuth()
  src/components/AccountDrawer.tsx
  src/components/ExhInfoCard.tsx
  src/components/StayStatusCard.tsx
  src/layouts/Main.tsx
  src/libs/auth.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/CheckOutScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/exhibition/EnterScan.tsx
  src/pages/exhibition/ExitScan.tsx
Labels: refactor

#97 #92 iPad 用 UI
  src/App.tsx
  src/components/AccountDrawer.tsx
  src/components/GuestScan.tsx
  src/components/SideNav.tsx
  src/components/TopBar.tsx
  src/layouts/Main.tsx
  src/layouts/Tablet.tsx
  src/libs/routes.ts
  src/pages/Account.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
Labels: design, enhancement

#108 #96 直接入力モーダルを上付きに
  src/components/DirectInputModal.tsx
Labels: bug, iOS

#109 #45 PTR をリロードボタンで置き換え
  package.json
  src/components/PullToRefresh.tsx
  src/components/ReloadButton.tsx
  src/pages/executive/AllExhStatus.tsx
  src/pages/exhibition/ScanHistory.tsx
  yarn.lock
Labels: bug, enhancement

#107 #105 ログインボタンの挙動を改善
  src/pages/Login.tsx
Labels: enhancement

#102 #88 QRコードをスキャンしたときにエラー表示が消えるように
  src/components/GuestScan.tsx
Labels: bug

#106 #104 meta theme-color を動的に背景色と同期
  src/App.tsx
  src/components/LayoutWrapper.tsx
  src/components/ProvidersProvider.tsx
  src/layouts/Main.tsx
  src/layouts/Tablet.tsx
  src/libs/themeMode.ts
Labels: enhancement, refactor

#111 #110 行動履歴タイムライン
  src/components/ActivityLogTimeline.tsx
  src/pages/executive/GuestInfo.tsx
Labels: enhancement

#103 #98 auth class を hooks で置き換え
  src/App.tsx
  src/components/AccountDrawer.tsx
  src/components/AccountIcon.tsx
  src/components/AuthContext.tsx
  src/components/BottomNav.tsx
  src/components/ExhInfoCard.tsx
  src/components/SideNav.tsx
  src/components/StayStatusCard.tsx
  src/components/TopBar.tsx
  src/layouts/Main.tsx
  src/libs/auth.ts
  src/libs/auth/@types.ts
  src/libs/auth/useAuth.ts
  src/libs/auth/useRequirePermission.ts
  src/pages/Account.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/executive/AllExhStatus.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/CheckOutScan.tsx
  src/pages/executive/GuestInfo.tsx
  src/pages/exhibition/EnterScan.tsx
  src/pages/exhibition/ExitScan.tsx
  src/pages/exhibition/ScanHistory.tsx
Labels: refactor

#112 #29 アイコン画像表示
  src/components/AccountDrawer.tsx
  src/components/AccountIcon.tsx
  src/components/ExhInfoCard.tsx
  src/components/SideNav.tsx
  src/components/StayStatusCard.tsx
  src/components/TopBar.tsx
  src/libs/useExhibitionImageUrl.tsx
  src/pages/Account.tsx
  src/pages/executive/AllExhStatus.tsx
  src/pages/executive/GuestInfo.tsx
  yarn.lock
Labels: design, enhancement

#113 #87 予約・ゲストのアイコンを変更
  src/components/GuestScan.tsx
  src/components/MaterialSvgIcons.tsx
  src/pages/executive/CheckInScan.tsx
  src/pages/executive/GuestInfo.tsx
Labels: design, enhancement
